### ISSUE TITLE
How to delete all the messages ?

### ISSUE THREAD

**Issue by xerosanyam** [emqtt/emq-retainer#36]
I have retained mqtt messages on disk. I would like to delete all of these messages. Please suggest a way to do this. Thanks

**Comment by HJianBo** [comment]
@xerosanyam The `emqttd_ctl` tool not able to delete retained messages in the current version! But you can do it with following steps:
**Step1:** Enter EMQ server console
```
./bin/emqttd attach
```

**Step2:**  Clear retained message table by calling mnesia API
```
> mnesia:clear_table(mqtt_retained).
```

**Step3:** Enter `<Ctrl> + D` to exist services console

**Comment by emqplus** [comment]
@HJianBo Please add two CLIs for the retainer plugin:

1. `retainer info`: Show the count of retained messages
2. `retainer clean` Clean all retained messages.

**Comment by emqplus** [comment]
Added the `retainer` CLI in PR: https://github.com/emqtt/emq-retainer/pull/37. @xerosanyam Please close the issue.

**Comment by xerosanyam** [comment]
thanks @emqplus
