### ISSUE TITLE
Retained messages still get lost after EMQTT broker restart.

### ISSUE THREAD

**Issue by miks** [emqtt/emq-retainer#46]
I'm still getting retained messages lost with 2.3.4 EMQ on broker restart.
My configuration:
```
##--------------------------------------------------------------------
## Retainer Module
##--------------------------------------------------------------------

## Where to store the retained messages.
## Notice that all nodes in a cluster are to have the same storage_type.
##
## Value: ram | disc | disc_only
##  - ram: memory only
##  - disc: both memory and disc
##  - disc_only: disc only
##
## Default: ram
retainer.storage_type = disc

## Maximum number of retained messages allowed.
##
## Value: Number >= 0
retainer.max_message_num = 1000000

## Maximum payload size of a retained message.
##
## Value: Bytes
retainer.max_payload_size = 64KB

## Expiration interval of the retained messages. Never expire if the value is 0.
##
## Value: Duration
##  - h: hour
##  - m: minute
##  - s: second
##
## Examples:
##  - 2h:  2 hours
##  - 30m: 30 minutes
##  - 20s: 20 seconds
##
## Defaut: 0
retainer.expiry_interval = 0
```

**Comment by turtleDeng** [comment]
@miks 
https://github.com/emqtt/emq-retainer/blob/master/etc/emq_retainer.conf#L14
retainer.storage_type default is ram. Please delete the default configuration generated file: 
```
./bin/emqttd stop
rm -rf data/mnesia/*
./bin/emqttd start
```

**Comment by miks** [comment]
Maybe it's useful to add this information also to docs?
I mean, you will always have messages stored in ram and therefore data/mnesia/* for ram usage.
After changing storage type to disk it's hard to imagine this extra step involved.

**Comment by miks** [comment]
I'm still losing retained messages after restarts even with data deletion.
Can I help with some kind of debug?

**Comment by emqplus** [comment]
@miks Do you mean losing retained messages even using the `disc` or `disc_only` storage type?

**Comment by miks** [comment]
`disc`.
Scenario is following: 
1) our application always set 3 retained messages on start.
2) so I started application and got those 3 retained messages on EMQ dashboard
3) I restarted emqqtd and there is 0 retained messages after restart on EMQ dashboard.

**Comment by emqplus** [comment]
@miks I cannot reproduce the issue. The steps:

1. Start the EMQ broker and then publish 3 retained messages via mosquitto client.

```
mosquitto_pub -t t1 -r -m m1
mosquitto_pub -t t2 -r -m m2
mosquitto_pub -t t3 -r -m m3
```

2. The Stats of Dashboard shows there are still 6 retained messages. Query the retained topics via CLI:

```
MacBook-Air-2:emqttd feng$ ./bin/emqttd_ctl retainer topics
$SYS/brokers
$SYS/brokers/emq@127.0.0.1/sysdescr
$SYS/brokers/emq@127.0.0.1/version
t1
t2
t3
```
3. Reboot the EMQ broker and check the Stats again.

**Comment by miks** [comment]
@emqplus it's all good now 👍 
Please, document this issue so you don't get another couple of tickets that messages is not stored in disk after changing that setting :)

**Comment by emqplus** [comment]
@miks @turtleDeng @grutabow  I submit a PR #47 to fix the issue. We don't need delete `data/mnesia/*` to make the storage_type change take effect.

**Comment by iambudi** [comment]
The broker only return one last retained message when subscribe :
retainer.storage_type = disc

```
> 1. Start the EMQ broker and then publish 3 retained messages via mosquitto client to the same topic.
> mosquitto_pub -t t1 -r -m m1
> mosquitto_pub -t t1 -r -m m2
> mosquitto_pub -t t1 -r -m m3
> 2. ./bin/emqttd_ctl retainer info shows 3.
> 3. Reboot the EMQ broker and check the Stats again. Still 3.
> 4. Subscribe to topic mosquitto_sub -t t1 -v -q 2 -c
> I only get m3, m1 and m2 are not published.
> 5. ./bin/emqttd_ctl retainer info shows 3.
```
When i don't reboot the broker, only kill the mosquitto_sub and run it again, all the messages will be pushed on subscribe.

**Comment by iambudi** [comment]
I missunderstood about retained message. What i actually mean is persistent client sessions after broker restart.
